# Generated by Django 5.1.6 on 2025-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category_alter_product_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
