# Generated by Django 5.1.6 on 2025-04-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='title',
        ),
    ]
