# Generated by Django 5.1.6 on 2025-04-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='blog',
        #     name='created_date',
        # ),
    ]
