# Generated by Django 5.1.6 on 2025-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
