# Generated by Django 5.1.6 on 2025-04-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
